# python ./tools/train_izdnas_all.py --cfg config/search/izdnasV4-P5.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name EXP_NAME --nas DNAS-70 --zc naswot --lookup config/lookup/p5_rb5_gpu_overhead.yaml
# python ./tools/train_izdnas_all.py --cfg config/search/izdnasV4-P5.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name noPretrain --nas DNAS-70 --zc naswot
# python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S42.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name noPretrain-flops-zc-p5-70-S42-0417 --nas DNAS-70 --zc naswot
# python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S43.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name noPretrain-flops-zc-p5-70-S43-0417 --nas DNAS-70 --zc naswot
# python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S44.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name noPretrain-flops-zc-p5-70-S44-0417 --nas DNAS-70 --zc naswot
# python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S45.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name noPretrain-flops-zc-p5-70-S45-0417 --nas DNAS-70 --zc naswot
python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S42.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name Pretrain-Bias-Group-20e-flops-zc-p5-70-S42-0422 --nas DNAS-70 --zc naswot
python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S43.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name Pretrain-Bias-Group-20e-flops-zc-p5-70-S43-0422 --nas DNAS-70 --zc naswot
python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S44.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name Pretrain-Bias-Group-20e-flops-zc-p5-70-S44-0422 --nas DNAS-70 --zc naswot
python ./tools/train_izdnas.py --cfg config/search/izdnasV4-P5-S45.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-P5.yaml --device 0 --exp_name Pretrain-Bias-Group-20e-flops-zc-p5-70-S45-0422 --nas DNAS-70 --zc naswot
# python ./tools/train_izdnas_all.py --cfg config/search/izdnasV4-Tiny.yaml --data ./config/dataset/voc_dnas.yaml --hyp ./config/training/hyp.zerocost.yaml --model config/model/Search-YOLOv4-Tiny.yaml --device 0 --exp_name tiny-noPretrain-7-S44-0418 --nas DNAS-7 --zc naswot --lookup config/lookup/p5_tiny_rb5_gpu_overhead.yaml
# cd ../ScaledYOLOv4-NAS
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/noPretrain-flops-zc-p5-70-S42-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name noPretrain-flops-zc-p5-70-S42-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/Pretrain-20e-flops-zc-p5-70-S42-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name Pretrain-20e-flops-zc-p5-70-S42-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/noPretrain-flops-zc-p5-70-S43-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name noPretrain-flops-zc-p5-70-S43-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/Pretrain-20e-flops-zc-p5-70-S43-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name Pretrain-20e-flops-zc-p5-70-S43-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/noPretrain-flops-zc-p5-70-S44-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name noPretrain-flops-zc-p5-70-S44-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/Pretrain-20e-flops-zc-p5-70-S44-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name Pretrain-20e-flops-zc-p5-70-S44-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/noPretrain-flops-zc-p5-70-S45-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name noPretrain-flops-zc-p5-70-S45-0417
# python train.py --batch-size 32 --img-size 416 --data voc.yaml --hyp ./data/hyp.finetune.yaml --cfg ../ZeroDNAS/experiments/workspace/train/Pretrain-20e-flops-zc-p5-70-S45-0417/model/phase2_naswot-best_f70.yaml  --weights '' --device 0 --name Pretrain-20e-flops-zc-p5-70-S45-0417