stage:1-gamma:0.25-depth:1: 
  latency: 9.4592
  mean: 9.4592
  variance: 0.0
stage:1-gamma:0.25-depth:3: 
  latency: 11.6182
  mean: 11.6182
  variance: 0.0
stage:1-gamma:0.25-depth:7: 
  latency: 15.735
  mean: 15.735
  variance: 0.0
stage:1-gamma:0.25-depth:15: 
  latency: 23.818
  mean: 23.818
  variance: 0.0
stage:1-gamma:0.5-depth:1: 
  latency: 13.1097
  mean: 13.1097
  variance: 0.0
stage:1-gamma:0.5-depth:15: 
  latency: 60.4307
  mean: 60.4307
  variance: 0.0
stage:1-gamma:0.5-depth:7: 
  latency: 33.5098
  mean: 33.5098
  variance: 0.0
stage:1-gamma:0.5-depth:3: 
  latency: 20.2601
  mean: 20.2601
  variance: 0.0
stage:1-gamma:0.75-depth:15: 
  latency: 119.8939
  mean: 119.8939
  variance: 0.0
stage:1-gamma:0.75-depth:3: 
  latency: 34.1788
  mean: 34.1788
  variance: 0.0
stage:1-gamma:0.75-depth:1: 
  latency: 19.2058
  mean: 19.2058
  variance: 0.0
stage:1-gamma:0.75-depth:7: 
  latency: 63.5404
  mean: 63.5404
  variance: 0.0
stage:2-gamma:0.25-depth:1: 
  latency: 8.4337
  mean: 8.4337
  variance: 0.0
stage:2-gamma:0.25-depth:3: 
  latency: 10.3445
  mean: 10.3445
  variance: 0.0
stage:2-gamma:0.25-depth:7: 
  latency: 14.0759
  mean: 14.0759
  variance: 0.0
stage:2-gamma:0.25-depth:15: 
  latency: 21.8705
  mean: 21.8705
  variance: 0.0
stage:2-gamma:0.5-depth:1: 
  latency: 12.0791
  mean: 12.0791
  variance: 0.0
stage:2-gamma:0.5-depth:15: 
  latency: 56.6715
  mean: 56.6715
  variance: 0.0
stage:2-gamma:0.5-depth:7: 
  latency: 31.3472
  mean: 31.3472
  variance: 0.0
stage:2-gamma:0.5-depth:3: 
  latency: 18.6587
  mean: 18.6587
  variance: 0.0
stage:2-gamma:0.75-depth:15: 
  latency: 113.063
  mean: 113.063
  variance: 0.0
stage:2-gamma:0.75-depth:3: 
  latency: 31.0292
  mean: 31.0292
  variance: 0.0
stage:2-gamma:0.75-depth:1: 
  latency: 17.4625
  mean: 17.4625
  variance: 0.0
stage:2-gamma:0.75-depth:7: 
  latency: 59.5344
  mean: 59.5344
  variance: 0.0
stage:3-gamma:0.25-depth:1: 
  latency: 8.4722
  mean: 8.4722
  variance: 0.0
stage:3-gamma:0.25-depth:3: 
  latency: 10.3053
  mean: 10.3053
  variance: 0.0
stage:3-gamma:0.25-depth:7: 
  latency: 14.0761
  mean: 14.0761
  variance: 0.0
stage:3-gamma:0.25-depth:15: 
  latency: 21.7968
  mean: 21.7968
  variance: 0.0
stage:3-gamma:0.5-depth:1: 
  latency: 12.2228
  mean: 12.2228
  variance: 0.0
stage:3-gamma:0.5-depth:15: 
  latency: 58.2712
  mean: 58.2712
  variance: 0.0
stage:3-gamma:0.5-depth:7: 
  latency: 31.8493
  mean: 31.8493
  variance: 0.0
stage:3-gamma:0.5-depth:3: 
  latency: 18.9997
  mean: 18.9997
  variance: 0.0
stage:3-gamma:0.75-depth:15: 
  latency: 118.0716
  mean: 118.0716
  variance: 0.0
stage:3-gamma:0.75-depth:3: 
  latency: 32.2196
  mean: 32.2196
  variance: 0.0
stage:3-gamma:0.75-depth:1: 
  latency: 17.6961
  mean: 17.6961
  variance: 0.0
stage:3-gamma:0.75-depth:7: 
  latency: 61.6431
  mean: 61.6431
  variance: 0.0
stage:4-gamma:0.25-depth:1: 
  latency: 9.0234
  mean: 9.0234
  variance: 0.0
stage:4-gamma:0.25-depth:3: 
  latency: 10.9629
  mean: 10.9629
  variance: 0.0
stage:4-gamma:0.25-depth:7: 
  latency: 14.6726
  mean: 14.6726
  variance: 0.0
stage:4-gamma:0.25-depth:15: 
  latency: 22.3518
  mean: 22.3518
  variance: 0.0
stage:4-gamma:0.5-depth:1: 
  latency: 13.3187
  mean: 13.3187
  variance: 0.0
stage:4-gamma:0.5-depth:15: 
  latency: 66.4622
  mean: 66.4622
  variance: 0.0
stage:4-gamma:0.5-depth:7: 
  latency: 35.7761
  mean: 35.7761
  variance: 0.0
stage:4-gamma:0.5-depth:3: 
  latency: 20.9413
  mean: 20.9413
  variance: 0.0
stage:4-gamma:0.75-depth:15: 
  latency: 135.4179
  mean: 135.4179
  variance: 0.0
stage:4-gamma:0.75-depth:3: 
  latency: 36.6534
  mean: 36.6534
  variance: 0.0
stage:4-gamma:0.75-depth:1: 
  latency: 19.4823
  mean: 19.4823
  variance: 0.0
stage:4-gamma:0.75-depth:7: 
  latency: 68.9131
  mean: 68.9131
  variance: 0.0
stage:5-gamma:0.25-depth:1: 
  latency: 13.1392
  mean: 13.1392
  variance: 0.0
stage:5-gamma:0.25-depth:3: 
  latency: 16.8688
  mean: 16.8688
  variance: 0.0
stage:5-gamma:0.25-depth:7: 
  latency: 24.284
  mean: 24.284
  variance: 0.0
stage:5-gamma:0.25-depth:15: 
  latency: 38.5391
  mean: 38.5391
  variance: 0.0
stage:5-gamma:0.5-depth:1: 
  latency: 20.208
  mean: 20.208
  variance: 0.0
stage:5-gamma:0.5-depth:15: 
  latency: 111.0981
  mean: 111.0981
  variance: 0.0
stage:5-gamma:0.5-depth:7: 
  latency: 59.9752
  mean: 59.9752
  variance: 0.0
stage:5-gamma:0.5-depth:3: 
  latency: 33.0011
  mean: 33.0011
  variance: 0.0
stage:5-gamma:0.75-depth:15: 
  latency: 171.4156
  mean: 171.4156
  variance: 0.0
stage:5-gamma:0.75-depth:3: 
  latency: 46.5221
  mean: 46.5221
  variance: 0.0
stage:5-gamma:0.75-depth:1: 
  latency: 25.9714
  mean: 25.9714
  variance: 0.0
stage:5-gamma:0.75-depth:7: 
  latency: 87.4902
  mean: 87.4902
  variance: 0.0
stage:6-gamma:0.25-depth:0: 
  latency: 1.2706
  mean: 1.2706
  variance: 0.0
stage:6-gamma:0.25-depth:3: 
  latency: 7.2382
  mean: 7.2382
  variance: 0.0
stage:6-gamma:0.25-depth:6: 
  latency: 13.2474
  mean: 13.2474
  variance: 0.0
stage:6-gamma:0.25-depth:9: 
  latency: 19.1247
  mean: 19.1247
  variance: 0.0
stage:6-gamma:0.5-depth:0: 
  latency: 1.7915
  mean: 1.7915
  variance: 0.0
stage:6-gamma:0.5-depth:3: 
  latency: 13.1413
  mean: 13.1413
  variance: 0.0
stage:6-gamma:0.5-depth:9: 
  latency: 35.2009
  mean: 35.2009
  variance: 0.0
stage:6-gamma:0.5-depth:6: 
  latency: 24.224
  mean: 24.224
  variance: 0.0
stage:6-gamma:0.75-depth:0: 
  latency: 2.3447
  mean: 2.3447
  variance: 0.0
stage:6-gamma:0.75-depth:3: 
  latency: 19.5188
  mean: 19.5188
  variance: 0.0
stage:6-gamma:0.75-depth:6: 
  latency: 36.4822
  mean: 36.4822
  variance: 0.0
stage:6-gamma:0.75-depth:9: 
  latency: 54.0079
  mean: 54.0079
  variance: 0.0
stage:7-gamma:0.25-depth:0: 
  latency: 1.4071
  mean: 1.4071
  variance: 0.0
stage:7-gamma:0.25-depth:3: 
  latency: 7.2213
  mean: 7.2213
  variance: 0.0
stage:7-gamma:0.25-depth:6: 
  latency: 13.0067
  mean: 13.0067
  variance: 0.0
stage:7-gamma:0.25-depth:9: 
  latency: 19.0759
  mean: 19.0759
  variance: 0.0
stage:7-gamma:0.5-depth:0: 
  latency: 1.8012
  mean: 1.8012
  variance: 0.0
stage:7-gamma:0.5-depth:3: 
  latency: 11.537
  mean: 11.537
  variance: 0.0
stage:7-gamma:0.5-depth:9: 
  latency: 30.6252
  mean: 30.6252
  variance: 0.0
stage:7-gamma:0.5-depth:6: 
  latency: 21.0877
  mean: 21.0877
  variance: 0.0
stage:7-gamma:0.75-depth:0: 
  latency: 2.4667
  mean: 2.4667
  variance: 0.0
stage:7-gamma:0.75-depth:3: 
  latency: 18.372
  mean: 18.372
  variance: 0.0
stage:7-gamma:0.75-depth:6: 
  latency: 34.2594
  mean: 34.2594
  variance: 0.0
stage:7-gamma:0.75-depth:9: 
  latency: 50.468
  mean: 50.468
  variance: 0.0
stage:8-gamma:0.25-depth:0: 
  latency: 1.2772
  mean: 1.2772
  variance: 0.0
stage:8-gamma:0.25-depth:3: 
  latency: 7.3618
  mean: 7.3618
  variance: 0.0
stage:8-gamma:0.25-depth:6: 
  latency: 13.3802
  mean: 13.3802
  variance: 0.0
stage:8-gamma:0.25-depth:9: 
  latency: 19.5133
  mean: 19.5133
  variance: 0.0
stage:8-gamma:0.5-depth:0: 
  latency: 1.7973
  mean: 1.7973
  variance: 0.0
stage:8-gamma:0.5-depth:3: 
  latency: 13.0431
  mean: 13.0431
  variance: 0.0
stage:8-gamma:0.5-depth:9: 
  latency: 35.1261
  mean: 35.1261
  variance: 0.0
stage:8-gamma:0.5-depth:6: 
  latency: 24.0667
  mean: 24.0667
  variance: 0.0
stage:8-gamma:0.75-depth:0: 
  latency: 2.3499
  mean: 2.3499
  variance: 0.0
stage:8-gamma:0.75-depth:3: 
  latency: 19.6226
  mean: 19.6226
  variance: 0.0
stage:8-gamma:0.75-depth:6: 
  latency: 36.7869
  mean: 36.7869
  variance: 0.0
stage:8-gamma:0.75-depth:9: 
  latency: 53.6515
  mean: 53.6515
  variance: 0.0
stage:9-gamma:0.25-depth:0: 
  latency: 1.8315
  mean: 1.8315
  variance: 0.0
stage:9-gamma:0.25-depth:3: 
  latency: 10.7618
  mean: 10.7618
  variance: 0.0
stage:9-gamma:0.25-depth:6: 
  latency: 19.6179
  mean: 19.6179
  variance: 0.0
stage:9-gamma:0.25-depth:9: 
  latency: 28.6709
  mean: 28.6709
  variance: 0.0
stage:9-gamma:0.5-depth:0: 
  latency: 2.9281
  mean: 2.9281
  variance: 0.0
stage:9-gamma:0.5-depth:3: 
  latency: 22.7763
  mean: 22.7763
  variance: 0.0
stage:9-gamma:0.5-depth:9: 
  latency: 60.7635
  mean: 60.7635
  variance: 0.0
stage:9-gamma:0.5-depth:6: 
  latency: 41.803
  mean: 41.803
  variance: 0.0
stage:9-gamma:0.75-depth:0: 
  latency: 3.4615
  mean: 3.4615
  variance: 0.0
stage:9-gamma:0.75-depth:3: 
  latency: 30.0576
  mean: 30.0576
  variance: 0.0
stage:9-gamma:0.75-depth:6: 
  latency: 57.07
  mean: 57.07
  variance: 0.0
stage:9-gamma:0.75-depth:9: 
  latency: 82.5326
  mean: 82.5326
  variance: 0.0